### ISSUE TITLE
BOOLEAN / BOOL support not working for introspection of tables

### ISSUE THREAD

**Issue by clach04** [ActianCorp/ingres_sa_dialect#13]
SELECT queries on objects work fine but not metadata lookup calls. E.g. test case:

    import os
    import sys

    import sqlalchemy

    print('Python %s on %s' % (sys.version, sys.platform))
    print('SQLAlchemy %s' % sqlalchemy.__version__)
    con_str = os.environ.get('DBNAME', 'ingres:///demodb')  # default to local demodb
    #con_str = 'ingres://dbuser:PASSWORD@HOSTNAME:27832/db'  # remote database called "db"
    engine = sqlalchemy.create_engine(con_str)
    connection = engine.connect()
    #print(connection.dialect.__class__)
    print(connection.dialect.__module__)
    print(sys.modules[connection.dialect.__module__])
    print('SQLAlchemy dialect %r' % connection.dialect.__class__.__name__)
    query = 'SELECT boolean(0) FROM iidbconstants'
    for row in connection.execute(sqlalchemy.text(query)):
        print(row)

    i = sqlalchemy.inspect(connection)
    try:
        connection.execute(sqlalchemy.text("DROP TABLE bool_test"))
    except:
        pass  # I really don't care... well I'm hoping and assuming it's not there.
    connection.execute(sqlalchemy.text("CREATE TABLE bool_test (col1 varchar(10), col2 boolean)"))
    print(i.get_columns('bool_test'))

fails with:

    (py3venv) C:\code\py\sqlalchemy\ingres_sa_dialect>python boolean_test.py
    Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
    SQLAlchemy 1.4.0b1
    ingres_sa_dialect.pyodbc
    <module 'ingres_sa_dialect.pyodbc' from 'c:\\code\\py\\sqlalchemy\\ingres_sa_dialect\\lib\\ingres_sa_dialect\\pyodbc.py'>
    SQLAlchemy dialect 'Ingres_pyodbc'
    (False,)
    Traceback (most recent call last):
      File "boolean_test.py", line 26, in <module>
        print(i.get_columns('bool_test'))
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\engine\reflection.py", line 468, in get_columns
        conn, table_name, schema, info_cache=self.info_cache, **kw
      File "<string>", line 2, in get_columns
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\engine\reflection.py", line 55, in cache
        ret = fn(self, con, *args, **kw)
      File "c:\code\py\sqlalchemy\ingres_sa_dialect\lib\ingres_sa_dialect\base.py", line 342, in get_columns
        coldata['type'] = ischema_names[coltype]
    KeyError: 'BOOLEAN'

**Comment by clach04** [comment]
Confirmed fixed in internal ticket II-10889
