### ISSUE TITLE
Reflection error with langchain

### ISSUE THREAD

**Issue by Statisticonomicon** [ActianCorp/ingres_sa_dialect#22]
import sys
    import sqlalchemy

    from langchain.sql_database import SQLDatabase

    print('Python %s on %s' % (sys.version, sys.platform))
    print('SQLAlchemy %r' % sqlalchemy.__version__)

    con_str = 'ingres:///demodb'  # local demodb

    db = SQLDatabase.from_uri(con_str)

--------------------------------------------------------------------------------

(base) C:\Users\kbonikos>python test2.py
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32
SQLAlchemy '2.0.16'
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1408, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\kbonikos\test2.py", line 14, in <module>
    db = SQLDatabase.from_uri(con_str)
  File "C:\Users\kbonikos\AppData\Roaming\Python\Python310\site-packages\langchain\sql_database.py", line 113, in from_uri
    return cls(create_engine(database_uri, **_engine_args), **kwargs)
  File "C:\Users\kbonikos\AppData\Roaming\Python\Python310\site-packages\langchain\sql_database.py", line 56, in __init__
    self._inspector.get_table_names(schema=schema)
  File "C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\engine\reflection.py", line 396, in get_table_names
    return self.dialect.get_table_names(
  File "<string>", line 2, in get_table_names
  File "C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\engine\reflection.py", line 97, in cache
    ret = fn(self, con, *args, **kw)
  File "c:\users\kbonikos\ingres_sa_dialect\lib\ingres_sa_dialect\base.py", line 486, in get_table_names
    rs = connection.execute(sqltext)
  File "C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: "\n            SELECT\n                table_name\n            FROM\n                iitables\n            WHERE\n                table_type = 'T'\n                AND table_owner != '$ingres'\n                AND table_name NOT LIKE 'ii%'"

**Comment by clach04** [comment]
@hab6 seen with both version 1.x and 2.x

**Comment by clach04** [comment]
Unclear if this is a langchain issue or a reflection issue in Ingres SA

**Comment by clach04** [comment]
@Statisticonomicon I'd like to confirm the version (and components) in use:
* https://pypi.org/project/langchain/
* https://github.com/hwchase17/langchain
* https://python.langchain.com/en/latest/

**Comment by Statisticonomicon** [comment]
langchain                     0.0.188

**Comment by clach04** [comment]
Rough test case:

    pip install langchain  # ...
    set DATABSE_URI variable ...
    python test_case.py

test_case.py

    import os
    import sys

    import sqlalchemy

    from langchain.sql_database import SQLDatabase


    print('Python %s on %s' % (sys.version, sys.platform))
    print('SQLAlchemy %r' % sqlalchemy.__version__)

    con_str = os.environ['DATABSE_URI']

    db = SQLDatabase.from_uri(con_str)

**Comment by clach04** [comment]
Pure SQLAlchemy test case, without langchain:

    # https://github.com/ActianCorp/ingres_sa_dialect/issues/22

    import os
    import sys

    import sqlalchemy

    import ingres_sa_dialect  # diagnostic test

    import langchain
    from langchain.sql_database import SQLDatabase


    print('Python %s on %s' % (sys.version, sys.platform))
    print('SQLAlchemy %r' % sqlalchemy.__version__)
    print('langchain %r' % langchain.__version__)

    driver_name = os.environ.get('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME') or 'Actian'
    print('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME %r' % driver_name)
    # set SQLALCHEMY_INGRES_ODBC_DRIVER_NAME=Ingres Y1

    con_str = os.environ['DATABASE_URI']
    # DATABASE_URI=ingres:///demodb
    # set DATABASE_URI=ingres:///demodb


    #db = SQLDatabase.from_uri(con_str)
    # Below is pure SA test case

    engine = sqlalchemy.create_engine(con_str)

    schema = None  # matches langchain usage in sql_database.SQLDatabase init
    inspector = sqlalchemy.inspect(engine)
    inspector.get_table_names(schema=schema)


Output:

    (py310venv) C:\code\py>python issue_22_sans_langchain.py
    Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
    SQLAlchemy '2.0.16'
    langchain '0.0.200'
    SQLALCHEMY_INGRES_ODBC_DRIVER_NAME 'Ingres Y1'
    0 ('u',)
    0 ('u',) 0
    -9
    (c_void_p(1791303484480), 1, 1, -8, -9, 510, 0, <cparam 'P' (0x000001A17E44A990)>, c_longlong(510), <cparam 'P' (0x000001A17FE27388)>)
    Traceback (most recent call last):
      File "C:\py310venv\lib\site-packages\sqlalchemy\engine\base.py", line 1408, in execute
        meth = statement._execute_on_connection
    AttributeError: 'str' object has no attribute '_execute_on_connection'

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\code\py\issue_22_sans_langchain.py", line 34, in <module>
        inspector.get_table_names(schema=schema)
      File "C:\py310venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 396, in get_table_names
        return self.dialect.get_table_names(
      File "<string>", line 2, in get_table_names
      File "C:\py310venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 97, in cache
        ret = fn(self, con, *args, **kw)
      File "C:\py310venv\lib\site-packages\ingres_sa_dialect\base.py", line 486, in get_table_names
        rs = connection.execute(sqltext)
      File "C:\py310venv\lib\site-packages\sqlalchemy\engine\base.py", line 1410, in execute
        raise exc.ObjectNotExecutableError(statement) from err
    sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: "\n            SELECT\n                table_name\n            FROM\n                iitables\n
                WHERE\n                table_type = 'T'\n                AND table_owner != '$ingres'\n                AND table_name NOT LIKE 'ii%'"

**Comment by clach04** [comment]
Quick fix is to wrap the SQL used for meta data look up in sqlalchemy.text ... But later on get errors that look confusing about not using tuples. This may be due to pyx functions which don;t give complete context. With an old SQ 1.4 area one sees the error related to expectation of dictionary in result set. Still early days, needs testing with both 1.x and 2.x. New test case, without longchain:

    # https://github.com/ActianCorp/ingres_sa_dialect/issues/22

    import os
    import sys

    import sqlalchemy

    import ingres_sa_dialect  # diagnostic test

    #import langchain
    #from langchain.sql_database import SQLDatabase


    print('Python %s on %s' % (sys.version, sys.platform))
    print('SQLAlchemy %r' % sqlalchemy.__version__)
    #print('langchain %r' % langchain.__version__)

    driver_name = os.environ.get('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME') or 'Actian'
    print('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME %r' % driver_name)
    # set SQLALCHEMY_INGRES_ODBC_DRIVER_NAME=Ingres Y1

    con_str = os.environ['DATABASE_URI']
    # DATABASE_URI=ingres:///demodb
    # set DATABASE_URI=ingres:///demodb


    #db = SQLDatabase.from_uri(con_str)
    # Below is pure SA test case

    engine = sqlalchemy.create_engine(con_str)

    schema = None  # matches langchain usage in sql_database.SQLDatabase init
    inspector = sqlalchemy.inspect(engine)
    inspector.get_table_names(schema=schema)

    metadata = sqlalchemy.MetaData()
    view_support = False

    metadata.reflect(
                views=view_support,
                bind=engine,
                #only=list(self._usable_tables),
                schema=schema,
            )

quick fix for one function:

    def get_table_names(self, connection, schema=None, **kw):
    ....
        sqltext = sqlalchemy.text(sqltext)
    ...

**Comment by clach04** [comment]
(py3venv) C:\code\py\sqlalchemy\ingres_sa_dialect>git diff
    diff --git a/lib/ingres_sa_dialect/base.py b/lib/ingres_sa_dialect/base.py
    index b542d99..abfc06a 100644
    --- a/lib/ingres_sa_dialect/base.py
    +++ b/lib/ingres_sa_dialect/base.py
    @@ -306,6 +306,9 @@ class IngresDialect(default.DefaultDialect):

             rs = None
             columns = []
    +        sqltext = sqlalchemy.text(sqltext)
    +        #params = tuple(params)
    +
             try:
                 rs = connection.execute(sqltext, params)

    @@ -476,9 +479,10 @@ class IngresDialect(default.DefaultDialect):
                 sqltext += """
                     AND table_owner != '$ingres'
                     AND table_name NOT LIKE 'ii%'"""
    -
    +
             rs = None
    -
    +        sqltext = sqlalchemy.text(sqltext)
    +
             try:
                 if params:
                     rs = connection.execute(sqltext, params)

    (py3venv) C:\code\py\sqlalchemy\ingres_sa_dialect>python C:\code\py\issue_22_sans_langchain.py
    Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
    SQLAlchemy '1.4.0b1'
    SQLALCHEMY_INGRES_ODBC_DRIVER_NAME 'Ingres Y1'
    Traceback (most recent call last):
      File "C:\code\py\issue_22_sans_langchain.py", line 43, in <module>
        schema=schema,
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\sql\schema.py", line 4272, in reflect
        Table(name, self, **reflect_opts)
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\sql\schema.py", line 535, in __new__
        metadata._remove_table(name, schema)
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\util\langhelpers.py", line 69, in __exit__
        exc_value, with_traceback=exc_tb,
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\util\compat.py", line 169, in raise_
        raise exception
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\sql\schema.py", line 530, in __new__
        table._init(name, metadata, *args, **kw)
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\sql\schema.py", line 609, in _init
        resolve_fks=resolve_fks,
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\sql\schema.py", line 639, in _autoload
        _extend_on=_extend_on,
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\engine\reflection.py", line 745, in reflect_table
        table_name, schema, **table.dialect_kwargs
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\engine\reflection.py", line 468, in get_columns
        conn, table_name, schema, info_cache=self.info_cache, **kw
      File "<string>", line 2, in get_columns
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\engine\reflection.py", line 55, in cache
        ret = fn(self, con, *args, **kw)
      File "c:\code\py\sqlalchemy\ingres_sa_dialect\lib\ingres_sa_dialect\base.py", line 313, in get_columns
        rs = connection.execute(sqltext, params)
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1072, in execute
        return meth(self, multiparams, params, util.immutabledict())
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\sql\elements.py", line 290, in _execute_on_connection
        self, multiparams, params, execution_options
      File "c:\code\py\sqlalchemy\lib\sqlalchemy\engine\base.py", line 1169, in _execute_clauseelement
        keys = list(distilled_params[0].keys())
    AttributeError: 'list' object has no attribute 'keys'

**Comment by Statisticonomicon** [comment]
Hello all,

I just implemented the changes outlined in the attached document, i.e.
I have made some edits to the file because I use conda so I don't forget where to copy stuff.
My warehouse was running and the table does exist.

1. removed sqlalchemy
2. installed sqlalchemy 1.4.29
3. installed the dialect and copied it
4. modified the dialect initiation file and reflection file

**I did not install the API Logic Server
My code still does not work.

Please help resolve this,everyone is asking me when I will have this working on AVL.**

My code minus API key:
**import os
os.environ['OPENAI_API_KEY'] = "iamkeepingthisasecret"

from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
from langchain.agents import AgentExecutor
from langchain.agents.agent_types import AgentType

import sqlalchemy #(from this we get create_engine)
import ingres_sa_dialect
db = SQLDatabase.from_uri('ingres://kostas.bonikos:demo@av-q3lcxefzo0mo.avstage.actiandatacloud.com:27832/db')

toolkit = SQLDatabaseToolkit(db=db, llm=OpenAI(temperature=0))

agent_executor = create_sql_agent(
    llm=OpenAI(temperature=0),
    toolkit=toolkit,
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
)

agent_executor.run("count the records")**

And this is the response I get:

**---------------------------------------------------------------------------
NoSuchTableError                          Traceback (most recent call last)
Cell In[1], line 14
     12 import sqlalchemy #(from this we get create_engine)
     13 import ingres_sa_dialect
---> 14 db = SQLDatabase.from_uri('ingres://kostas.bonikos:demo@av-q3lcxefzo0mo.avstage.actiandatacloud.com:27832/db')
     16 toolkit = SQLDatabaseToolkit(db=db, llm=OpenAI(temperature=0))
     18 agent_executor = create_sql_agent(
     19     llm=OpenAI(temperature=0),
     20     toolkit=toolkit,
     21     verbose=True,
     22     agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
     23 )

File ~\AppData\Roaming\Python\Python310\site-packages\langchain\sql_database.py:124, in SQLDatabase.from_uri(cls, database_uri, engine_args, **kwargs)
    122 """Construct a SQLAlchemy engine from URI."""
    123 _engine_args = engine_args or {}
--> 124 return cls(create_engine(database_uri, **_engine_args), **kwargs)

File ~\AppData\Roaming\Python\Python310\site-packages\langchain\sql_database.py:111, in SQLDatabase.__init__(self, engine, schema, metadata, ignore_tables, include_tables, sample_rows_in_table_info, indexes_in_table_info, custom_table_info, view_support, max_string_length)
    109 self._metadata = metadata or MetaData()
    110 # including view support if view_support = true
--> 111 self._metadata.reflect(
    112     views=view_support,
    113     bind=self._engine,
    114     only=list(self._usable_tables),
    115     schema=self._schema,
    116 )

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py:4756, in MetaData.reflect(self, bind, schema, views, only, extend_existing, autoload_replace, resolve_fks, **dialect_kwargs)
   4754 for name in load:
   4755     try:
-> 4756         Table(name, self, **reflect_opts)
   4757     except exc.UnreflectableTableError as uerr:
   4758         util.warn("Skipping table %s: %s" % (name, uerr))

File <string>:2, in __new__(cls, *args, **kw)

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\util\deprecations.py:309, in deprecated_params.<locals>.decorate.<locals>.warned(fn, *args, **kwargs)
    302     if m in kwargs:
    303         _warn_with_version(
    304             messages[m],
    305             versions[m],
    306             version_warnings[m],
    307             stacklevel=3,
    308         )
--> 309 return fn(*args, **kwargs)

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py:606, in Table.__new__(cls, *args, **kw)
    604     return table
    605 except Exception:
--> 606     with util.safe_reraise():
    607         metadata._remove_table(name, schema)

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     68     self._exc_info = None  # remove potential circular references
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:
     75     if not compat.py3k and self._exc_info and self._exc_info[1]:
     76         # emulate Py3K's behavior of telling us when an exception
     77         # occurs in an exception handler.

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\util\compat.py:207, in raise_(***failed resolving arguments***)
    204     exception.__cause__ = replace_context
    206 try:
--> 207     raise exception
    208 finally:
    209     # credit to
    210     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    211     # as the __traceback__ object creates a cycle
    212     del exception, replace_context, from_, with_traceback

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py:602, in Table.__new__(cls, *args, **kw)
    600 metadata._add_table(name, schema, table)
    601 try:
--> 602     table._init(name, metadata, *args, **kw)
    603     table.dispatch.after_parent_attach(table, metadata)
    604     return table

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py:677, in Table._init(self, name, metadata, *args, **kwargs)
    673 # load column definitions from the database if 'autoload' is defined
    674 # we do it after the table is in the singleton dictionary to support
    675 # circular foreign keys
    676 if autoload:
--> 677     self._autoload(
    678         metadata,
    679         autoload_with,
    680         include_columns,
    681         _extend_on=_extend_on,
    682         resolve_fks=resolve_fks,
    683     )
    685 # initialize all the column, etc. objects.  done after reflection to
    686 # allow user-overrides
    688 self._init_items(
    689     *args,
    690     allow_replacements=extend_existing or keep_existing or autoload
    691 )

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\sql\schema.py:712, in Table._autoload(self, metadata, autoload_with, include_columns, exclude_columns, resolve_fks, _extend_on)
    710 insp = inspection.inspect(autoload_with)
    711 with insp._inspection_context() as conn_insp:
--> 712     conn_insp.reflect_table(
    713         self,
    714         include_columns,
    715         exclude_columns,
    716         resolve_fks,
    717         _extend_on=_extend_on,
    718     )

File C:\ProgramData\anaconda3\lib\site-packages\sqlalchemy\engine\reflection.py:789, in Inspector.reflect_table(self, table, include_columns, exclude_columns, resolve_fks, _extend_on)
    787 # NOTE: support tables/views with no columns
    788 if not found_table and not self.has_table(table_name, schema):
--> 789     raise exc.NoSuchTableError(table_name)
    791 self._reflect_pk(
    792     table_name, schema, table, cols_by_orig_name, exclude_columns
    793 )
    795 self._reflect_fk(
    796     table_name,
    797     schema,
   (...)
    803     reflection_options,
    804 )

NoSuchTableError: Predictive_ShoppingCartAbandoned**

**Comment by hab6** [comment]
I took the test case from the [June 14 post](https://github.com/ActianCorp/ingres_sa_dialect/issues/22#issuecomment-1592138066) by @clach04 which avoids using langchain and got beyond the `sqlalchemy.exc.ObjectNotExecutableError` by using Python dictionaries to handle parameters in various places of [base.py](https://github.com/ActianCorp/ingres_sa_dialect/blob/master/lib/ingres_sa_dialect/base.py) in the Ingres dialect.

But now am encountering a different problem in the SQLAlchemy [reflection.py](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/engine/reflection.py) code, which seems very odd. The stack dump has only references to the SQLAlchemy code and no references to the Ingres dialect.

#### New Error
```
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 1703, in _reflect_pk
    for pk in pk_cons["constrained_columns"]
TypeError: list indices must be integers or slices, not str
```

I tried with SQLAlchemy versions `2.0.23, 2.0.22, 2.0.0, 1.4.50, 1.4.42, 1.4.23` and all got the same error.

#### Test case
```
import os
import sys

import sqlalchemy

import ingres_sa_dialect  # diagnostic test

print('Python %s on %s' % (sys.version, sys.platform))
print('SQLAlchemy %r' % sqlalchemy.__version__)

driver_name = os.environ.get('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME') or 'Actian'
print('SQLALCHEMY_INGRES_ODBC_DRIVER_NAME %r' % driver_name)

con_str = os.environ['DATABASE_URI']

engine = sqlalchemy.create_engine(con_str)

schema = None  # matches langchain usage in sql_database.SQLDatabase init
inspector = sqlalchemy.inspect(engine)
inspector.get_table_names(schema=schema)

metadata = sqlalchemy.MetaData()
view_support = False

metadata.reflect(
            views=view_support,
            bind=engine,
            #only=list(self._usable_tables),
            schema=schema
        )
```

#### Stack dump with the error
```
(.venv) λ python test1.py
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
SQLAlchemy '2.0.23'
SQLALCHEMY_INGRES_ODBC_DRIVER_NAME 'Actian II'
Traceback (most recent call last):
  File "C:\Users\mhabiger\Data\work\saDialect\test9\test1.py", line 46, in <module>
    metadata.reflect(
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\sql\schema.py", line 5800, in reflect
    Table(name, self, **reflect_opts)
  File "<string>", line 2, in __new__
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\sql\schema.py", line 436, in __new__
    return cls._new(*args, **kw)
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\sql\schema.py", line 490, in _new
    with util.safe_reraise():
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\sql\schema.py", line 486, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\sql\schema.py", line 866, in __init__
    self._autoload(
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\sql\schema.py", line 898, in _autoload
    conn_insp.reflect_table(
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 1566, in reflect_table
    self._reflect_pk(
  File "C:\Users\mhabiger\Data\work\saDialect\test9\.venv\lib\site-packages\sqlalchemy\engine\reflection.py", line 1703, in _reflect_pk
    for pk in pk_cons["constrained_columns"]
TypeError: list indices must be integers or slices, not str
```

**Comment by hab6** [comment]
#### Status update

As previously noted, the following error:

     sqlalchemy.exc.ObjectNotExecutableError: Not an executable object

is resolved with this change in several places in `/lib/ingres_sa_dialect/base.py` of the Ingres dialect:  

     sqltext = sqlalchemy.text(sqltext)

The change is needed because the function **`sqlalchemy.engine.Connection.execute`** expects a **`sqlalchemy.sql.expression.Executable`** object instead of a Python text sequence type **`str`**.

The next error:  

     TypeError: list indices must be integers or slices, not str

is resolved with the following changes in the SQLAlchemy module `lib\sqlalchemy\engine\reflection.py`:

Function: `def _reflect_pk(`

from:  

     for pk in pk_cons["constrained_columns"]
     ...
     table.primary_key.name = pk_cons.get("name")
     ...
     table.primary_key.comment = pk_cons.get("comment", None)

to:  

     for pk in pk_cons
     ...
     table.primary_key.name = pk_cons[0]
     ...
     table.primary_key.comment = None

The changes to function `_reflect_pk` were given to me by @Statisticonomicon from another Actian developer.

With the given changes, the test cases provided above by @Statisticonomicon and @clach04 execute successfully.

I will pursue updating the Ingres dialect with the needed changes and also determine if the latter issue is a bug in SQLAlchemy or in the Ingres dialect.

**Comment by clach04** [comment]
@hab6 I think this is the issue discussed about name case of objects (if not, lets get the description updated and a link to the issue).
    
    select * FROM iidbcapabilities WHERE cap_capability like '%CASE%'
    Executing . . .
     
     
    +--------------------------------+--------------------------------+
    |cap_capability                  |cap_value                       |
    +--------------------------------+--------------------------------+
    |MIXEDCASE_NAMES                 |N                               |
    |DB_NAME_CASE                    |LOWER                           |
    |DB_DELIMITED_CASE               |LOWER                           |
    |DB_REAL_USER_CASE               |LOWER                           |
    +--------------------------------+--------------------------------+

Is the sanity check needed to make decisions. Also compare with ODBC metadata query interface, new option, 139795:

    (ATTENTION, ODBC)
    PowerBI cannot access tables with mixedcase if DB_NAME_CASE is set as LOWER and
    DB_DELIMITED_CASE is set as MIXED.
    Default behaviour of odbc driver - converting catalog object name case based on
    DB_NAME_CASE & DB_DELIMITED_CASE is disabled. This can be enabled by 
    passing new driver option METADATA_FORCE_CASE=Y as connection string.
    (139795)

At least two options:
1. use ODBC meta interface - I'm recommending **against** this option, as this will ONLY work with ODBC driver as implementation (I would like us to support multiple drivers)
2. update/add logic to sqlalchemy-ingres to implement similar logic as the ODBC driver. Worth pinging connectivity team and/or checking drive metadata source code (or ping me to locate change for the SIR number above).

**Comment by clach04** [comment]
With the Actian Data Platform (nee Avalanche) **different** results are expected for the query above in comment https://github.com/ActianCorp/sqlalchemy-ingres/issues/22#issuecomment-1986428822

**Comment by hab6** [comment]
@clach04 I think this reflection issue is not directly related to the case of identifier objects for which I have opened #37

**Comment by hab6** [comment]
This reflection problem is now fixed with code changes from #23 and #31. The current [sqlalchemy headrev](https://github.com/ActianCorp/sqlalchemy-ingres) contains the fixes in version `0.0.5`, which as of the time of this update are not yet available at https://pypi.org/project/sqlalchemy-ingres/.

**Comment by clach04** [comment]
@hab6 does this mean you'd like to get a new release posted or want to get more changes in first? Your call.

**Comment by hab6** [comment]
@clach04 I think a new release should be posted now to make the latest fixes available.

**Comment by hab6** [comment]
Fixes for this issue are available in SQLAlchemy-Ingres release [0.0.6](https://github.com/ActianCorp/sqlalchemy-ingres/releases/tag/v0.0.6) which is now published to [PyPi](https://pypi.org/project/sqlalchemy-ingres/).

With this latest release, the original provided test case that uses `langchain` and also the other reflection test cases that are given in this issue now run successfully.
